import { Post, PostService } from 'alexandrejonathas-alganews-sdk'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import FeaturedPost from '../components/FeaturedPost.component'

interface HomeProps {
  posts: Post.Paginated
}

export default function Home (props: HomeProps) {

  const { posts } = props

  return (
    <div >
      <Head>
        <title>AlgaNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        posts?.content && <FeaturedPost postSummary={posts.content[0]} />
      }
    </div>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) => {
  const { page } = context.query
  const posts = await PostService.getAllPosts({page: page ? Number(page) : 0})
  return { 
    props: {
      posts
    }
  } 
}
